[workspace]
members = [
    "cli",
    "microkernel",
    "common",
    "backend",
    "plugins/plugin_lossy_ddl",
    "plugins/plugin_slowlog",
    "plugins/plugin_github_issue",
    "plugins/plugin_rca_engine",
    "plugins/plugin_sql_editor",
    "plugins/plugin_profile_collector",
    "plugins/plugin_alert_webhook",
    "plugins/plugin_multiplexer", 
    "plugins/plugin_tihc_backend", 
    "plugins/plugin_tihc_mcp_server", 
    "plugins/plugin_tihc_mcp_client"]
resolver = "2"
