[package]
name = "tihc"
version = "0.1.0"
authors = ["jansu-dev <jan-su-dev@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.32.0", features = ["yaml"] }
docx-rs = "0.2"
ssh2 = "0.9"
chrono = "0.4"
thiserror = "1.0"
anyhow = "1.0"
pbr = "1.0.4"
colored = "2.0.0"