[package]
name = "ticheck"
version = "0.1.0"
authors = ["jansu-dev <jan-su-dev@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clap = { version = "3.0.0-rc.9", features = ["derive"] }
docx-rs = "0.2"
ssh2 = "0.9"
chrono = "0.4"

