[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]

clap = { version = "4", features = ["derive"] }
core = { path = "../core" }
anyhow = "1"

chrono = { version = "0.4", features = ["clock"] }
